// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: import_of_legacy_library_into_null_safe
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eKPWRnzdQuWPlX0RBdmkbfhUcK3L3eY',
    appId: '1:1053968925919:web:5c76e05f43f568736dd56a',
    messagingSenderId: '1053968925919',
    projectId: 'examen-ordinario-f9b84',
    authDomain: 'examen-ordinario-f9b84.firebaseapp.com',
    storageBucket: 'examen-ordinario-f9b84.appspot.com',
    measurementId: 'G-GNEGD7F1FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVqRXCunD5uoILUEI65W8crJOvwa-90dw',
    appId: '1:1053968925919:android:b2df1da522c33f686dd56a',
    messagingSenderId: '1053968925919',
    projectId: 'examen-ordinario-f9b84',
    storageBucket: 'examen-ordinario-f9b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC76wPkkexFEbQWUHw18vf5OoZLq5Ycw0s',
    appId: '1:1053968925919:ios:7ee51d38882a1fe76dd56a',
    messagingSenderId: '1053968925919',
    projectId: 'examen-ordinario-f9b84',
    storageBucket: 'examen-ordinario-f9b84.appspot.com',
    iosClientId:
        '1053968925919-7j1b3fas2c74r3bfe18st0jnorvj9k2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicaionOrdinario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC76wPkkexFEbQWUHw18vf5OoZLq5Ycw0s',
    appId: '1:1053968925919:ios:7ee51d38882a1fe76dd56a',
    messagingSenderId: '1053968925919',
    projectId: 'examen-ordinario-f9b84',
    storageBucket: 'examen-ordinario-f9b84.appspot.com',
    iosClientId:
        '1053968925919-7j1b3fas2c74r3bfe18st0jnorvj9k2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplicaionOrdinario',
  );
}
